name: Benchmark

# only one can tun at a time.
# Actions access a common cache entry and may corrupt it.
concurrency: cd-benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Get the entire git history to walk commit history on head branch
          fetch-depth: 0
          # Do not checkout merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.16.0"

      - name: GA cache benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Print git data
        run: |
          echo "BEFORE FETCH"
          git branch
          git log -n 2
          echo "FETCH"
          git fetch origin main
          echo "AFTER FETCH"
          git branch
          git log -n 2

      # Run benchmark with custom tooling and stores the output to a file
      - name: Run performance tests
        run: yarn benchmark --local ./cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
