name: Compare Benchmark

# only one can tun at a time.
# Actions access a common cache entry and may corrupt it.
concurrency: cd-benchmark-compare-${{ github.ref }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compare-js-runtimes: 
    uses: ChainSafe/benchmark/.github/workflows/compare-js-runtimes.yml@nh/compare
    with: 
      node-version: 22
      bun-version: latest
      deno-version: v2.x
      command: ./bin/index.js 
      setup: build
      files: test/perf/**/*.test.ts

