name: Compare Benchmark

# only one can tun at a time.
# Actions access a common cache entry and may corrupt it.
concurrency: cd-benchmark-compare-${{ github.ref }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark-nodejs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Run performance tests on node
        run: yarn benchmark --local ./nodejs-benchmark --noThrow ${{ github.event_name == 'push' }} --defaultBranch ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive nodejs benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-benchmark
          path: ./nodejs-benchmark

  benchmark-bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run performance tests on bun
        run: bun run --bun benchmark --local ./bun-benchmark --noThrow ${{ github.event_name == 'push' }} --defaultBranch ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive bun benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bun-benchmark
          path: bun-benchmark

  benchmark-deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Dependencies
        run: deno install

      - name: Run performance tests on bun
        run: deno run -A benchmark --local ./deno-benchmark --noThrow ${{ github.event_name == 'push' }} --defaultBranch ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive deno benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deno-benchmark
          path: deno-benchmark

  benchmark-compare:
    runs-on: ubuntu-latest
    needs: [benchmark-deno, benchmark-bun, benchmark-nodejs]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Download all benchmark artifacts
        uses: actions/download-artifact@v4

      - name: Run comparison
        run: node --loader ts-node/esm ./src/cli/cli.ts cmp nodejs-benchmark deno-benchmark bun-benchmark
