name: Benchmark

# only one can tun at a time.
# Actions access a common cache entry and may corrupt it.
concurrency: cd-benchmark-${{ github.ref }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  local:
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Get the entire git history to walk commit history on head branch
          fetch-depth: 0
          # Do not checkout merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.16.0"

      - name: GA cache benchmark data
        uses: actions/cache@v1
        # WARNING! Using the approach benchmark data won't be persisted if the workflow fails
        if: always()
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark-2

      - name: Install
        run: yarn install --frozen-lockfile

      # Run benchmark with custom tooling and stores the output to a file
      - name: Run performance tests
        run: yarn benchmark --local ./cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check files
        if: always()
        run: |
          echo "./cache/history"
          ls -ltr ./cache/history
          echo "./cache/latest"
          ls -ltr ./cache/latest
          cat ./cache/latest/main

  s3:
    if: always()
    runs-on: ubuntu-latest
    # Ensure both don't run at the same time
    needs: local

    steps:
      - uses: actions/checkout@v2
        with:
          # Get the entire git history to walk commit history on head branch
          fetch-depth: 0
          # Do not checkout merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.16.0"

      - name: Install
        run: yarn install --frozen-lockfile

      # Run benchmark with custom tooling and stores the output to a file
      - name: Run performance tests
        run: yarn benchmark --s3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # S3 credentials
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
