name: Release please
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  publish:
    permissions:
      contents: write
      pull-requests: write
      id-token: write # The OIDC ID token is used for authentication with JSR.
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: ${{ steps.release.outputs.release_created }}

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 22.x
          cache: yarn

      - name: Install Yarn
        run: yarn --immutable
        if: ${{ steps.release.outputs.release_created }}

      - name: Build
        run: yarn build
        if: ${{ steps.release.outputs.release_created }}

      - name: Install latest npm
        run: npm install -g npm@latest
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to npm
        run: npm publish --access public
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to JSR
        run: yarn jsr publish
        if: ${{ steps.release.outputs.release_created }}
