name: Tests

on: [pull_request, push]

jobs:
  test-node:
    name: Test Node
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
    runs-on: ubuntu-latest
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{matrix.node}}
      - name: Install
        run: yarn install --frozen-lockfile
      # </common-build>
      - name: Build
        run: yarn build      
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test:unit

  test-bun:
    name: Test Bun
    runs-on: ubuntu-latest
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "22"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: bun run --bun build
      - name: Unit tests
        run: bun run --bun test:unit
